[theme]
primaryColor = "#D0001B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF5F5"
textColor = "#1D1D1F"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
